name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: pod install
    - name: Run Tests
      run: |
          bundle install
          bundle exec fastlane test
